/*
 * Internal module API header file.
 *
 * Generated by SIP 4.16.5 on Wed Mar 11 11:57:09 2015
 */

#ifndef _helloworldAPI_H
#define _helloworldAPI_H


#include <sip.h>

/*
 * Convenient names to refer to various strings defined in this module.
 * Only the class names are part of the public API.
 */
#define sipNameNr_getGreeting 0
#define sipName_getGreeting &sipStrings_helloworld[0]
#define sipNameNr_HelloWorld 12
#define sipName_HelloWorld &sipStrings_helloworld[12]
#define sipNameNr_helloworld 23
#define sipName_helloworld &sipStrings_helloworld[23]

#define sipMalloc                   sipAPI_helloworld->api_malloc
#define sipFree                     sipAPI_helloworld->api_free
#define sipBuildResult              sipAPI_helloworld->api_build_result
#define sipCallMethod               sipAPI_helloworld->api_call_method
#define sipCallErrorHandler         sipAPI_helloworld->api_call_error_handler
#define sipParseResultEx            sipAPI_helloworld->api_parse_result_ex
#define sipParseResult              sipAPI_helloworld->api_parse_result
#define sipParseArgs                sipAPI_helloworld->api_parse_args
#define sipParseKwdArgs             sipAPI_helloworld->api_parse_kwd_args
#define sipParsePair                sipAPI_helloworld->api_parse_pair
#define sipCommonDtor               sipAPI_helloworld->api_common_dtor
#define sipConvertFromSequenceIndex sipAPI_helloworld->api_convert_from_sequence_index
#define sipConvertFromVoidPtr       sipAPI_helloworld->api_convert_from_void_ptr
#define sipConvertToVoidPtr         sipAPI_helloworld->api_convert_to_void_ptr
#define sipAddException             sipAPI_helloworld->api_add_exception
#define sipNoFunction               sipAPI_helloworld->api_no_function
#define sipNoMethod                 sipAPI_helloworld->api_no_method
#define sipAbstractMethod           sipAPI_helloworld->api_abstract_method
#define sipBadClass                 sipAPI_helloworld->api_bad_class
#define sipBadCatcherResult         sipAPI_helloworld->api_bad_catcher_result
#define sipBadCallableArg           sipAPI_helloworld->api_bad_callable_arg
#define sipBadOperatorArg           sipAPI_helloworld->api_bad_operator_arg
#define sipTrace                    sipAPI_helloworld->api_trace
#define sipTransferBack             sipAPI_helloworld->api_transfer_back
#define sipTransferTo               sipAPI_helloworld->api_transfer_to
#define sipTransferBreak            sipAPI_helloworld->api_transfer_break
#define sipSimpleWrapper_Type       sipAPI_helloworld->api_simplewrapper_type
#define sipWrapper_Type             sipAPI_helloworld->api_wrapper_type
#define sipWrapperType_Type         sipAPI_helloworld->api_wrappertype_type
#define sipVoidPtr_Type             sipAPI_helloworld->api_voidptr_type
#define sipGetPyObject              sipAPI_helloworld->api_get_pyobject
#define sipGetAddress               sipAPI_helloworld->api_get_address
#define sipGetMixinAddress          sipAPI_helloworld->api_get_mixin_address
#define sipGetCppPtr                sipAPI_helloworld->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_helloworld->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_helloworld->api_is_py_method
#define sipCallHook                 sipAPI_helloworld->api_call_hook
#define sipEndThread                sipAPI_helloworld->api_end_thread
#define sipConnectRx                sipAPI_helloworld->api_connect_rx
#define sipDisconnectRx             sipAPI_helloworld->api_disconnect_rx
#define sipRaiseUnknownException    sipAPI_helloworld->api_raise_unknown_exception
#define sipRaiseTypeException       sipAPI_helloworld->api_raise_type_exception
#define sipBadLengthForSlice        sipAPI_helloworld->api_bad_length_for_slice
#define sipAddTypeInstance          sipAPI_helloworld->api_add_type_instance
#define sipFreeSipslot              sipAPI_helloworld->api_free_sipslot
#define sipSameSlot                 sipAPI_helloworld->api_same_slot
#define sipPySlotExtend             sipAPI_helloworld->api_pyslot_extend
#define sipConvertRx                sipAPI_helloworld->api_convert_rx
#define sipAddDelayedDtor           sipAPI_helloworld->api_add_delayed_dtor
#define sipCanConvertToType         sipAPI_helloworld->api_can_convert_to_type
#define sipConvertToType            sipAPI_helloworld->api_convert_to_type
#define sipForceConvertToType       sipAPI_helloworld->api_force_convert_to_type
#define sipCanConvertToEnum         sipAPI_helloworld->api_can_convert_to_enum
#define sipReleaseType              sipAPI_helloworld->api_release_type
#define sipConvertFromType          sipAPI_helloworld->api_convert_from_type
#define sipConvertFromNewType       sipAPI_helloworld->api_convert_from_new_type
#define sipConvertFromNewPyType     sipAPI_helloworld->api_convert_from_new_pytype
#define sipConvertFromEnum          sipAPI_helloworld->api_convert_from_enum
#define sipGetState                 sipAPI_helloworld->api_get_state
#define sipLong_AsUnsignedLong      sipAPI_helloworld->api_long_as_unsigned_long
#define sipExportSymbol             sipAPI_helloworld->api_export_symbol
#define sipImportSymbol             sipAPI_helloworld->api_import_symbol
#define sipFindType                 sipAPI_helloworld->api_find_type
#define sipFindNamedEnum            sipAPI_helloworld->api_find_named_enum
#define sipBytes_AsChar             sipAPI_helloworld->api_bytes_as_char
#define sipBytes_AsString           sipAPI_helloworld->api_bytes_as_string
#define sipString_AsASCIIChar       sipAPI_helloworld->api_string_as_ascii_char
#define sipString_AsASCIIString     sipAPI_helloworld->api_string_as_ascii_string
#define sipString_AsLatin1Char      sipAPI_helloworld->api_string_as_latin1_char
#define sipString_AsLatin1String    sipAPI_helloworld->api_string_as_latin1_string
#define sipString_AsUTF8Char        sipAPI_helloworld->api_string_as_utf8_char
#define sipString_AsUTF8String      sipAPI_helloworld->api_string_as_utf8_string
#define sipUnicode_AsWChar          sipAPI_helloworld->api_unicode_as_wchar
#define sipUnicode_AsWString        sipAPI_helloworld->api_unicode_as_wstring
#define sipConvertFromConstVoidPtr  sipAPI_helloworld->api_convert_from_const_void_ptr
#define sipConvertFromVoidPtrAndSize    sipAPI_helloworld->api_convert_from_void_ptr_and_size
#define sipConvertFromConstVoidPtrAndSize   sipAPI_helloworld->api_convert_from_const_void_ptr_and_size
#define sipInvokeSlot               sipAPI_helloworld->api_invoke_slot
#define sipInvokeSlotEx             sipAPI_helloworld->api_invoke_slot_ex
#define sipSaveSlot                 sipAPI_helloworld->api_save_slot
#define sipClearAnySlotReference    sipAPI_helloworld->api_clear_any_slot_reference
#define sipVisitSlot                sipAPI_helloworld->api_visit_slot
#define sipWrappedTypeName(wt)      ((wt)->type->td_cname)
#define sipDeprecated               sipAPI_helloworld->api_deprecated
#define sipKeepReference            sipAPI_helloworld->api_keep_reference
#define sipRegisterProxyResolver    sipAPI_helloworld->api_register_proxy_resolver
#define sipRegisterPyType           sipAPI_helloworld->api_register_py_type
#define sipTypeFromPyTypeObject     sipAPI_helloworld->api_type_from_py_type_object
#define sipTypeScope                sipAPI_helloworld->api_type_scope
#define sipResolveTypedef           sipAPI_helloworld->api_resolve_typedef
#define sipRegisterAttributeGetter  sipAPI_helloworld->api_register_attribute_getter
#define sipIsAPIEnabled             sipAPI_helloworld->api_is_api_enabled
#define sipSetDestroyOnExit         sipAPI_helloworld->api_set_destroy_on_exit
#define sipEnableAutoconversion     sipAPI_helloworld->api_enable_autoconversion
#define sipInitMixin                sipAPI_helloworld->api_init_mixin
#define sipExportModule             sipAPI_helloworld->api_export_module
#define sipInitModule               sipAPI_helloworld->api_init_module

/* These are deprecated. */
#define sipMapStringToClass         sipAPI_helloworld->api_map_string_to_class
#define sipMapIntToClass            sipAPI_helloworld->api_map_int_to_class
#define sipFindClass                sipAPI_helloworld->api_find_class
#define sipFindMappedType           sipAPI_helloworld->api_find_mapped_type
#define sipConvertToArray           sipAPI_helloworld->api_convert_to_array
#define sipConvertToTypedArray      sipAPI_helloworld->api_convert_to_typed_array
#define sipWrapper_Check(w)         PyObject_TypeCheck((w), sipAPI_helloworld->api_wrapper_type)
#define sipGetWrapper(p, wt)        sipGetPyObject((p), (wt)->type)
#define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->type, (s))
#define sipReleaseMappedType        sipReleaseType
#define sipCanConvertToInstance(o, wt, f)   sipCanConvertToType((o), (wt)->type, (f))
#define sipCanConvertToMappedType   sipCanConvertToType
#define sipConvertToInstance(o, wt, t, f, s, e)     sipConvertToType((o), (wt)->type, (t), (f), (s), (e))
#define sipConvertToMappedType      sipConvertToType
#define sipForceConvertToInstance(o, wt, t, f, s, e)    sipForceConvertToType((o), (wt)->type, (t), (f), (s), (e))
#define sipForceConvertToMappedType sipForceConvertToType
#define sipConvertFromInstance(p, wt, t)    sipConvertFromType((p), (wt)->type, (t))
#define sipConvertFromMappedType    sipConvertFromType
#define sipConvertFromNamedEnum(v, pt)  sipConvertFromEnum((v), ((sipEnumTypeObject *)(pt))->type)
#define sipConvertFromNewInstance(p, wt, t) sipConvertFromNewType((p), (wt)->type, (t))

/* The strings used by this module. */
extern const char sipStrings_helloworld[];

#define sipType_HelloWorld              sipModuleAPI_helloworld.em_types[0]
#define sipClass_HelloWorld             sipModuleAPI_helloworld.em_types[0]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_helloworld_HelloWorld;

/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_helloworld;
extern sipExportedModuleDef sipModuleAPI_helloworld;

#endif
