/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_java2com_COMProxy */

#ifndef _Included_com_example_java2com_COMProxy
#define _Included_com_example_java2com_COMProxy
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_java2com_COMProxy_DISPATCH_METHOD
#define com_example_java2com_COMProxy_DISPATCH_METHOD 1L
#undef com_example_java2com_COMProxy_DISPATCH_PROPERTYGET
#define com_example_java2com_COMProxy_DISPATCH_PROPERTYGET 2L
#undef com_example_java2com_COMProxy_DISPATCH_PROPERTYPUT
#define com_example_java2com_COMProxy_DISPATCH_PROPERTYPUT 4L
#undef com_example_java2com_COMProxy_DISPATCH_PROPERTYPUTREF
#define com_example_java2com_COMProxy_DISPATCH_PROPERTYPUTREF 8L
/*
 * Class:     com_example_java2com_COMProxy
 * Method:    Create
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_java2com_COMProxy_Create
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_java2com_COMProxy
 * Method:    Get
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_java2com_COMProxy_Get
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_java2com_COMProxy
 * Method:    Invoke
 * Signature: (Ljava/lang/String;I[Lcom/example/java2com/Variant;)Lcom/example/java2com/Variant;
 */
JNIEXPORT jobject JNICALL Java_com_example_java2com_COMProxy_Invoke
  (JNIEnv *, jobject, jstring, jint, jobjectArray);

/*
 * Class:     com_example_java2com_COMProxy
 * Method:    Destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_java2com_COMProxy_Destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_example_java2com_COMProxy
 * Method:    SetDebugEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_example_java2com_COMProxy_SetDebugEnabled
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
