package com.example.adf.view.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 12 16:10:29 CET 2014
// ---------------------------------------------------------------------
public interface SimpleTableAM extends ApplicationModule {
    void updateData(String theData);
}

