package com.example.adf.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 04 13:37:10 CET 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AddressVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AddressVOImpl() {
    }
    
    
    public void processData() {
    }
}

