package com.example.adf.view;

import com.example.adf.view.common.SimpleTableAM;

import oracle.jbo.server.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 12 16:09:33 CET 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SimpleTableAMImpl extends ApplicationModuleImpl implements SimpleTableAM {
    /**
     * This is the default constructor (do not remove).
     */
    public SimpleTableAMImpl() {
    }

    /**
     * Container's getter for AddressVO.
     * @return AddressVO
     */
    public AddressVOImpl getAddressVO() {
        return (AddressVOImpl) findViewObject("AddressVO");
    }

    public void updateData(String theData) {
        System.err.println("Updating data with " + theData);
    }
}
