#include <iostream>
#include "ExpressionParser.hpp"

int main(int argc, char *argv[]) {
    std::cout << "ExpressionParser example" << std::endl;

    ANTLR_UINT8*	    fName;

    if (argc < 2 || argv[1] == NULL) {
        std::cout << "Usage: ExpressionParser inputFile" << std::endl;
        return 1;
    } else {
        fName	= (ANTLR_UINT8*)argv[1];
    }

    ExpressionLexer::InputStreamType input(fName, ANTLR_ENC_8BIT);
    ExpressionLexer lxr(&input);	    // CLexerNew is generated by ANTLR
    ExpressionParser::TokenStreamType tstream(ANTLR_SIZE_HINT, lxr.get_tokSource() );
    ExpressionParser psr(&tstream);  // CParserNew is generated by ANTLR3

    psr.start();

    return 0;
}
