#!/bin/bash

usage() {
    echo "usage: $0 date"
    echo
    echo "  Lists all files together with their size"
    echo "  below the current directory tree which"
    echo "  have been modified after the given date."
    echo
    echo "  date has the format YYYY-MM-DD [HH:MM:SS]"
}

if [ $# -ne 1 ] ; then
    usage
    exit 1
fi

REFDATE=$1
COUNT=0
TOTALSIZE=0
MAXSIZE=4200000000    # ISO 9660 filesystem also has some overhead!
LISTNO=0

while read f
do
  FILENAME=`echo $f | sed -e "s,^./,,g"`
  SIZE=`stat --format="%s" "${FILENAME}"`
  (( COUNT++ ))
  TOTALSIZE=$((TOTALSIZE + SIZE))
  if [ ${TOTALSIZE} -gt ${MAXSIZE} ] ; then
    TOTALSIZE=${SIZE}
    (( LISTNO++ ))
  fi

  echo "/$FILENAME=$FILENAME" >> LIST${LISTNO}.lst
done < <( find . -type f -newermt ${REFDATE}  )

# echo "${COUNT} files with total size of ${TOTALSIZE}"

# mkisofs -path-list myfilelist

