#!/bin/bash

JAR=jar

if [ $# -eq 1 ] ; then
    PATTERN=$1
    for f in `find . \( -type f -o -type l \) -a -name "*.jar"`; do
        echo $f
        ${JAR} tvf $f | grep -i ${PATTERN}
    done
fi
 
