#!/bin/bash

# Add a prefix and a suffix to each line of a file
cat file | awk '{print "PREFIX"$0"SUFFIX"}'

# Colorize each line (light blue)
cat file | awk '{print "\x1b[1;34m"$0"\x1b[m"}'

# Colorize each line (red background)
cat file | awk '{print "\x1b[1;41m"$0"\x1b[m"}'
