#include <iostream>
#include "SimpleParser.hpp"

int main(int argc, char *argv[]) {
    std::cout << "SimpleParser example" << std::endl;

    ANTLR_UINT8*	    fName;

    if (argc < 2 || argv[1] == NULL) {
        std::cout << "Usage: SimpleParser inputFile" << std::endl;
        return 1;
    } else {
        fName	= (ANTLR_UINT8*)argv[1];
    }

    SimpleLexer::InputStreamType input(fName, ANTLR_ENC_8BIT);
    SimpleLexer lxr(&input);	    // CLexerNew is generated by ANTLR
    SimpleParser::TokenStreamType tstream(ANTLR_SIZE_HINT, lxr.get_tokSource() );
    SimpleParser psr(&tstream);  // CParserNew is generated by ANTLR3

    psr.r();

    return 0;
}
